#1 Prepare FS Lab
secs-dev/os-course pull request #3
Opened 2024-11-23 10:39 UTC by vityaman

- Переименовал `CT` в `VT`. (Надо бы где-то указать их авторство, а то некрасиво)
- Переименовал `networkfs` в `vtfs`
- Переместил часть про `networkfs` в конец
- Добавил часть про требование реализовать `ramfs`
- Подредачил кодстайл - чтобы все было `snake_case`

2024-11-24 21:20 UTC, e1turin commented on lab/vtfs/source/vtfs.c
> +  LOG("VT Flood!\n");
А может сделать типа LOG("VTFS joined kernel chat")

2024-11-24 21:22 UTC, e1turin commented on lab/vtfs/source/vtfs.c
> +  LOG("VT Mute!\n");
И соответственно `LOG("VTFS left the kernel")`

2024-11-24 21:22 UTC, e1turin commented on lab/vtfs/source/vtfs.c
> +MODULE_AUTHOR("vtshniks");
авторство под secs-dev?

2024-11-24 21:23 UTC, vityaman commented on lab/vtfs/source/vtfs.c
> +MODULE_AUTHOR("vtshniks");
Сам все поменяй, как хочешь

2024-11-25 00:07 UTC, e1turin requested changes

2024-11-25 07:58 UTC, vityaman commented on lab/vtfs/README.md
> +Давайте поймём, что эта функция делает. Файловой системе нужно знать, где находится корень файловой системы. Для этого в поле `s_root` мы записываем результат функции [d_make_root][16], передавая ему
polfik

2024-11-25 07:59 UTC, vityaman commented on lab/vtfs/README.md
> +sudo mount -t vtfs "<token>" "<path>"
пусть будет

2024-11-25 08:02 UTC, merged